# Generated by Django 5.1.3 on 2024-12-08 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_ac', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teknisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('nomor_hp', models.CharField(max_length=15)),
                ('spesialisasi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('teknisi', 'Teknisi')], max_length=10)),
                ('alamat', models.TextField()),
                ('nomor_hp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_servis', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('dikerjakan', 'Dikerjakan'), ('selesai', 'Selesai')], max_length=10)),
                ('deskripsi', models.TextField()),
                ('teknisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_ac.teknisi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_ac.user')),
            ],
        ),
    ]
